config/routes.rb
ProductFeedApp::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks", :registrations => 'registrations'}
                    
  resources :products

  get "users/:id" => "users#show", as: "user"

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :blurb, :category, :description, :images, :options, 
  	:price, :qty, :shipping_weight, :size, :subcategory, :title, 
  	:weight, :image
  validates :blurb, :length => { :maximum  => 140}

# for creating a user w/products
belongs_to :user
# for images
mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # for creating a user w/products
  has_many :products

  mount_uploader :image, ImageUploader

  # Setup accessible (or protected) attributes for your model
  attr_accessor :password, :password_confirmation, :current_password
  attr_accessible :email, :password, :password_confirmation, :remember_me, 
  :username, :current_password, :image
  # attr_accessible :title, :body

  validates_presence_of :username
  
  # Facebook Authentication (#360)
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		@products = Product.all
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end

  alias_method :facebook, :all

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /products
  # GET /products.json
  def index
    # for creating a user w/products
    @products = current_user.products
    # for showing current user profile info
    @current_user = current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    # for creating a user w/products
    @product = current_user.products.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update
  	# http://stackoverflow.com/questions/13436232/editing-users-with-devise-and-omniauth#comment18368874_13436232
    # @user = User.find(current_user.id)
    # email_changed = @user.email != params[:user][:email]
    # is_facebook_account = !@user.provider.blank?

    # successfully_updated = if !is_facebook_account
    #   @user.update_with_password(params[:user])
    # else
    #   @user.update_without_password(params[:user])
    # end

    # if successfully_updated
    #   # Sign in the user bypassing validation in case his password changed
    #   sign_in @user, :bypass => true
    #   redirect_to root_path
    # else
    #   render "edit"
    # end

    # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-account-without-providing-a-password
    # required for settings form to submit when password is left blank
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end

    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

#For Devise
	def create
	  user = User.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to root_url, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to root_url, :notice => "Signed up!"
		else
			render "new"
		end
	end

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= model_class = Product %>
<div class="page-header">
  <h1>Home</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Avatar</th> 
      <th>Username</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <!-- <th><model_class.human_attribute_name(:id)></th> -->
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:blurb) %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to (image_tag product.user.image_url(:small_avatar, @user).to_s), product.user %></td>
      	<td><%= link_to product.user.username, product.user %></td>
        <td><%=l product.created_at %></td>
        <td><%= link_to (image_tag product.image_url(:big_thumb).to_s), product_path(product) %></td>
        <!-- <td><link_to product.id, product_path(product)></td> -->
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.blurb %></td>
        <td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductFeedApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="container">
		<div id="user_nav">
			<% if user_signed_in? %>
		  		Logged in as <strong><%= current_user.email %></strong>.
		  		<%= link_to "Home", root_path %> |
		  		<!-- <link_to 'Explore'> | -->
		  		<%= link_to 'Sell', new_product_path %> |
		  		<!-- <link_to 'News'> | -->
		  		<%= link_to 'Profile', user_path(current_user) %> |
		  		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
			<% else %>
		  		<%= link_to "Sign up", new_user_registration_path %> |
		  		<%= link_to "Login", new_user_session_path %>
           <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
			<% end %>
		</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :qty, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :qty, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :blurb, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :blurb, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :weight, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :weight, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :shipping_weight, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :shipping_weight, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subcategory, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subcategory, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :size, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :size, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :options, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :options, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_path(current_user), :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1>Sell</h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @product.image_url.to_s %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @product.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qty) %>:</strong></dt>
  <dd><%= @product.qty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:blurb) %>:</strong></dt>
  <dd><%= @product.blurb %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @product.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shipping_weight) %>:</strong></dt>
  <dd><%= @product.shipping_weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @product.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subcategory) %>:</strong></dt>
  <dd><%= @product.subcategory %></dd>
  <dt><strong><%= model_class.human_attribute_name(:size) %>:</strong></dt>
  <dd><%= @product.size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:options) %>:</strong></dt>
  <dd><%= @product.options %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_path(current_user), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1>My Profile</h1>
</div>

<!-- user profile info -->
<table class="table table-striped">
  <thead>
     <tr>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= image_tag @user.image_url(:big_avatar).to_s %></td>
      <td><%= @user.username %></td>
    </tr>
  </tbody>
</table>

<div class="edit-profile">
| <%= link_to 'Edit Profile', edit_user_registration_path %> |
</div>

<div class="settings">
  <p>|   Settings   |</p> 
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:blurb) %></th>
    </tr>
  </thead>
  <tbody>
    <% @user.products.each do |product| %>
      <tr>
        <td><%=l product.created_at %></td>
        <td><%= link_to (image_tag product.image_url(:big_thumb).to_s), product_path(product) %></td>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.blurb %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>